language: node_js
node_js:
  - "7"

env:
  - AUTH=yes USER=patrick PASSWORD=swordfish
  - AUTH=no

sudo: required

services:
  - docker

before_install:
  - docker build -t urlshortener .
  - docker run -d -p 3000:3000 --name myshortener urlshortener

script: npm test

after_script: 
  - docker stop myshortener
  - docker rm myshortener

